### ISSUE TITLE
On boot2docker VM restart, boot2docker certificates stop working

### ISSUE THREAD

**Issue by taxilian** [boot2docker/boot2docker#968]
When I try to run:

    $ docker ps
    FATA[0000] An error occurred trying to connect: Get https://192.168.59.103:2376/v1.18/containers/json: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103

I can fix this easily:

    $ boot2docker stop
    $ boot2docker delete
    $ boot2docker initboot
    $ boot2docker start
    Waiting for VM and Docker daemon to start...
    .........................oooooooooooooooooo
    Started.
    Writing /Users/myuser/.boot2docker/certs/boot2docker-vm/ca.pem
    Writing /Users/myuser/.boot2docker/certs/boot2docker-vm/cert.pem
    Writing /Users/myuser/.boot2docker/certs/boot2docker-vm/key.pem
    Your environment variables are already set correctly.
    $ docker ps
    CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

However, if I restart the VM it stops working again immediately:

    $ boot2docker stop
    $ boot2docker start
    Waiting for VM and Docker daemon to start...
    ...................ooo
    Started.
    Writing /Users/myuser/.boot2docker/certs/boot2docker-vm/ca.pem
    Writing /Users/myuser/.boot2docker/certs/boot2docker-vm/cert.pem
    Writing /Users/myuser/.boot2docker/certs/boot2docker-vm/key.pem
    Your environment variables are already set correctly.
    $ docker ps
    FATA[0000] An error occurred trying to connect: Get https://192.168.59.103:2376/v1.18/containers/json: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103

This is 100% reproducible on both macs I've tried it on.

    $ docker --version
    Docker version 1.6.2, build 7c8fca2

    $ boot2docker version
    Boot2Docker-cli version: v1.7.0
    Git commit: 7d89508

My system information:

![screenshot 2015-07-02 15 35 24](https://cloud.githubusercontent.com/assets/224334/8488479/15a9d41c-20d0-11e5-8bfe-9259e9f01f41.png)

**Comment by larskanis** [comment]
This is a duplication of https://github.com/boot2docker/boot2docker/issues/824 . It will be fixed in boot2docker-1.7.1.

**Comment by aChase55** [comment]
When can this update be expected? The software is almost impossible to work with as is.

**Comment by garrettdreyfus** [comment]
I would also like to know when it is expected as well.

**Comment by larskanis** [comment]
boot2docker will usually be released together with docker. And docker just entered another rc cycle: https://github.com/docker/docker/releases

**Comment by damnhandy** [comment]
This issue is present on Windows 7 Enterprise as well.

**Comment by fmsouza** [comment]
I'm also having this issue in my Macbook Pro mid 2012, OSX 10.10.4. It never happened before the last month. Eveytime I finished working, I used to turn off the VM through ```boot2docker down``` and then turn it up again when beggining to work again with ```boot2docker up```, and then decided to just suspend the VM instead of turn off using ```boot2docker suspend```.

**Comment by damnhandy** [comment]
So far, it seems that 1.7.1 fixes this. Will verify on Windows 7 later today.

**Comment by radnor** [comment]
After installing 1.7.1 on top of 1.7.0 (after `boot2docker poweroff`) I received the same invalid certificate error message in Windows 7. 

However, running `boot2docker upgrade` then downloaded a 1.7.1 boot2docker.iso from github and now everything is fixed.

**Comment by pfortuna** [comment]
I did a clean install of 1.7.1 and after a boot2docker stop/start, I'm getting the invalid certificate error message. A clean install fixes this, but the problem seems to come back. Any ideas ?

**Comment by MoOx** [comment]
This update just worked for me on an existing image.

**Comment by jakirkham** [comment]
@tianon, looks like this can be closed as fixed.

**Comment by pfortuna** [comment]
@jakirkham not sure it should be closed. 1.7.1 didn't work for me.

**Comment by jakirkham** [comment]
@pfortuna, sorry, somehow missed that the issue reoccurred for you.

**Comment by Alino** [comment]
thanks god this has been fixed, I was going mad !

**Comment by timmles** [comment]
I vote this be closed as well. I was on boot2docker 1.5.0, I used `homebrew upgrade boot2docker` to upgrade. Using `boot2docker -v` it showed version 1.7.1, and the problem still remained. But I later found that the iso had not been updated, and once I ran `boot2docker download` the problem was resolved.

I can now run the following without errors:

    boot2docker destroy
    boot2docker init
    boot2docker start
    docker ps
    boot2docker stop
    boot2docker start
    docker ps

**Comment by jakirkham** [comment]
Unless @pfortuna could you please run the following `boot2docker version && docker version`. Also, try doing what @timmles has stated to ensure that you are using the latest ISO.
